version: "3.8"

services:
  front:
    build:
      dockerfile: "Dockerfile"
      context: "."
    volumes:
      - ./:/app:rw,cached
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
