name: jest-and-docker-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Goto client and run tests
        run: npm install && npm run test -- --passWithNoTests
